name: river
channels:
  - intel
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.7.0
  - appnope=0.1.0
  - astor=0.7.1
  - backcall=0.1.0
  - blas=1.0
  - c-ares=1.15.0
  - ca-certificates=2019.1.23
  - certifi=2018.1.18
  - cycler=0.10.0
  - decorator=4.3.2
  - entrypoints=0.3
  - freetype=2.9.1
  - gast=0.2.2
  - grpcio=1.14.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - intel-openmp=2019.1
  - intelpython=2019.3
  - ipykernel=5.1.0
  - ipython=7.3.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jinja2=2.10
  - jsonschema=2.6.0
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - jupyterlab=0.35.3
  - jupyterlab_server=0.2.0
  - keras=2.2.4
  - keras-applications=1.0.6
  - keras-base=2.2.4
  - keras-preprocessing=1.0.5
  - kiwisolver=1.0.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.36
  - libprotobuf=3.6.1
  - libsodium=1.0.16
  - markdown=3.0.1
  - markupsafe=1.1.1
  - matplotlib=3.0.2
  - mistune=0.8.4
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - nodejs=10.13.0
  - notebook=5.7.4
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openmp=2018.0.3
  - openssl=1.0.2r
  - pandas=0.24.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.4
  - patsy=0.5.1
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - protobuf=3.6.1
  - ptyprocess=0.6.0
  - pygments=2.3.1
  - pyparsing=2.3.1
  - python=3.6.6
  - python-dateutil=2.8.0
  - pytz=2018.9
  - pyyaml=3.13
  - pyzmq=18.0.0
  - readline=7.0
  - scikit-learn=0.20.2
  - scipy=1.2.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=40.8.0
  - six=1.12.0
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - tensorboard=1.12.2
  - tensorflow=1.12.0
  - tensorflow-base=1.12.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.33.1
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - pip:
    - bleach==3.1.0
prefix: /Users/mmngreco/miniconda3/envs/river

